In [1]:
%matplotlib inline

import pandas as pd
import numpy as np

import seaborn as sns

import matplotlib.pyplot as plt

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [5]:
import sys
sys.path.append("../gasopt/") # Adds higher directory to python modules path.

In [9]:
from data_load import furn_forecast_data_process

In [10]:
G = furn_forecast_data_process('../../mmk/data/gas-expense-10.19.xlsx')

In [11]:
G.head()

              dt_hour             1             2             3            4
0 2019-10-01 00:00:00  16775.333333  15930.833333  16521.166667    20.666667
1 2019-10-01 01:00:00  14845.500000  13519.666667  14620.166667  2003.000000
2 2019-10-01 02:00:00  13759.500000  13059.000000  13968.166667  2014.333333
3 2019-10-01 03:00:00  14503.666667  13382.666667  14211.833333  1833.166667
4 2019-10-01 04:00:00  13843.833333  13107.000000  14001.666667  3502.333333

In [13]:
from furnance_interface import furnace_forecast

In [14]:
from data_load import build_furn_dataset

In [30]:
F = furnace_forecast(G, horizon=24, furn_id=1)

100
200
300
400
500
600
VanillaRNN(
  (rnn): RNN(24, 10, batch_first=True)
  (fc): Linear(in_features=10, out_features=24, bias=True)
)
                                 Statespace Model Results
==========================================================================================
Dep. Variable:                                  y   No. Observations:                  672
Model:             SARIMAX(2, 1, 1)x(1, 1, 0, 24)   Log Likelihood               -5890.578
Date:                            Wed, 20 May 2020   AIC                          11791.155
Time:                                    16:26:44   BIC                          11813.517
Sample:                                         0   HQIC                         11799.831
                                            - 672
Covariance Type:                              opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
ar.L1          0.2592      0.102      2.544      0.011       0.059       0.459
ar.L2         -0.2543      0.062     -4.128      0.000      -0.375      -0.134
ma.L1         -0.5581      0.100     -5.559      0.000      -0.755      -0.361
ar.S.L24      -0.5132      0.035    -14.711      0.000      -0.582      -0.445
sigma2      6.143e+06   3.34e+05     18.386      0.000    5.49e+06     6.8e+06
===================================================================================
Ljung-Box (Q):                       96.95   Jarque-Bera (JB):               117.28
Prob(Q):                              0.00   Prob(JB):                         0.00
Heteroskedasticity (H):               1.31   Skew:                            -0.27
Prob(H) (two-sided):                  0.05   Kurtosis:                         5.02
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
Iteration:      1,   Func. Count:      6,   Neg. LLF: 2962.398426643573
Iteration:      2,   Func. Count:     14,   Neg. LLF: 2962.3850367542927
Iteration:      3,   Func. Count:     22,   Neg. LLF: 2962.363344458
Iteration:      4,   Func. Count:     28,   Neg. LLF: 2962.3618530349513
Iteration:      5,   Func. Count:     34,   Neg. LLF: 2962.3576105314205
Iteration:      6,   Func. Count:     40,   Neg. LLF: 2962.349277902923
Iteration:      7,   Func. Count:     46,   Neg. LLF: 2962.32034364478
Iteration:      8,   Func. Count:     52,   Neg. LLF: 2962.259924681594
Iteration:      9,   Func. Count:     58,   Neg. LLF: 2962.1536852680447
Iteration:     10,   Func. Count:     64,   Neg. LLF: 2962.065019613753
Iteration:     11,   Func. Count:     70,   Neg. LLF: 2962.0223181617257
Iteration:     12,   Func. Count:     76,   Neg. LLF: 2962.016954752863
Iteration:     13,   Func. Count:     82,   Neg. LLF: 2962.0169293695935
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 2962.016929370086
            Iterations: 13
            Function evaluations: 82
            Gradient evaluations: 13
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                      y   R-squared:                      -0.000
Mean Model:             Constant Mean   Adj. R-squared:                 -0.000
Vol Model:                      GARCH   Log-Likelihood:               -2962.02
Distribution:                  Normal   AIC:                           5932.03
Method:            Maximum Likelihood   BIC:                           5950.07
                                        No. Observations:                  672
Date:                Wed, May 20 2020   Df Residuals:                      668
Time:                        16:26:49   Df Model:                            4
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.1667      0.943      0.177      0.860 [ -1.681,  2.015]
                             Volatility Model
==========================================================================
                 coef    std err          t      P>|t|    95.0% Conf. Int.
--------------------------------------------------------------------------
omega         34.7693     18.887      1.841  6.563e-02   [ -2.248, 71.787]
alpha[1]       0.1747  4.218e-02      4.143  3.427e-05 [9.208e-02,  0.257]
beta[1]        0.7525  8.573e-02      8.777  1.672e-18   [  0.584,  0.921]
==========================================================================

Covariance estimator: robust

In [31]:
F

            FFNN           RNN       SARIMAX          ARCH
0   11824.761745  12023.141075  11960.926106  11961.092799
1   11800.599374  11157.934874  11947.746568  11947.913261
2   11738.343324  11684.524558  11934.567030  11934.733723
3   11829.450820  13228.838746  11921.387492  11921.554185
4   11729.762189  12174.213717  11908.207954  11908.374647
5   11770.681635  12013.617780  11895.028416  11895.195109
6   11666.452881  11338.125742  11881.848878  11882.015571
7   11849.959048  12620.647448  11868.669340  11868.836033
8   11603.534204  13535.094378  11855.489802  11855.656495
9   11784.907326  11275.164677  11842.310264  11842.476957
10  11687.516025  10911.820777  11829.130726  11829.297419
11  11664.704640  12369.675561  11815.951188  11816.117881
12  11727.667394  10796.973274  11802.771650  11802.938343
13  11745.791632  11578.476510  11789.592112  11789.758805
14  11763.734762  16167.039514  11776.412574  11776.579267
15  11725.947988  11925.820408  11763.233036  11763.399729
16  11558.108414   9812.895898  11750.053498  11750.220191
17  11632.682887  12271.732884  11736.873960  11737.040653
18  11739.698861  13017.977573  11723.694422  11723.861115
19  11521.890046  10585.466193  11710.514884  11710.681577
20  11677.173924  11370.703340  11697.335346  11697.502039
21  11679.109688  10929.169630  11684.155808  11684.322501
22  11545.459309   8846.033735  11670.976270  11671.142963
23  11636.325680  11519.603736  11657.796732  11657.963425