In [1]:
%matplotlib inline

import pandas as pd
import numpy as np

import seaborn as sns

import matplotlib.pyplot as plt

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [4]:
import sys
sys.path.append("../gasopt/") # Adds higher directory to python modules path.

In [5]:
from data_load import furn_optimization_data_process

In [18]:
T = pd.read_csv('test-slab-input-furn1.csv', ';', encoding='cp1251')

In [19]:
T

   length_s  width_s  weight_s  slab_temp  l_thick  dt_prev  row   mark
0      4800     1340    12.273      112.0      2.0    0.007    2  Ст3пс
1      4800     1340    12.240      745.0      2.0  134.657    1  Ст3пс
2      4800     1340    12.240      720.0      2.0    0.003    2  Ст3пс
3      5000     1340    12.780      243.0      2.0  235.523    1  Ст3пс
4      5000     1340    12.780      242.0      2.0    0.010    2  Ст3пс
5      5000     1340    12.784      434.0      2.0  596.834    1  Ст3пс
6      6000     1270    14.540      672.0      2.5    0.003    2  other
7      6000     1270    14.540       55.0      2.5  371.590    1  other
8      6000     1270    14.540      280.0      2.5    0.003    2  other
9      9500     1340    24.240      507.0      2.0  176.357    2  Ст3пс

In [20]:
G = furn_optimization_data_process('test-slab-input-furn1.csv')

In [21]:
G

,length_s,width_s,weight_s,slab_temp,l_thick,dt_prev,row,mark,area_s,vacant_area,...,mark_14,mark_15,mark_16,mark_17,mark_18,mark_19,mark_20,t_unl,temp_gain,heat_gain
0,4800,1340,12.273,112,2,0.007,2,Ст3пс,6432000,3216000.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1250,1138,13966.7
1,4800,1340,12.24,745,2,134.657,1,Ст3пс,6432000,3216000.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1250,505,6181.2
2,4800,1340,12.24,720,2,0.003,2,Ст3пс,6432000,3216000.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1250,530,6487.2
3,5000,1340,12.78,243,2,235.523,1,Ст3пс,6700000,2680000.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1250,1007,12869.5
4,5000,1340,12.78,242,2,0.01,2,Ст3пс,6700000,2680000.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1250,1008,12882.2
5,5000,1340,12.784,434,2,596.834,1,Ст3пс,6700000,2680000.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1250,816,10431.7
6,6000,1270,14.54,672,2.5,0.003,2,other,7620000,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1250,578,8404.12
7,6000,1270,14.54,55,2.5,371.59,1,other,7620000,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1250,1195,17375.3
8,6000,1270,14.54,280,2.5,0.003,2,other,7620000,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1250,970,14103.8
9,9500,1340,24.24,507,2,176.357,2,Ст3пс,12730000,3350000.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1250,743,18010.3

In [23]:
from furnance_interface import furnace_optimization

In [14]:
from data_load import build_furn_dataset

In [29]:
F = furnace_optimization(G, furn_id=1)

In [30]:
F

,agas_1,agas_2,agas_3,agas_4,agas_5,agas_6,agas_7l,agas_7r,agas_8l,agas_8r,igas_1,igas_2,igas_3,igas_4,igas_5,igas_6,igas_7l,igas_7r,igas_8l,igas_8r
0,914.709994,0.0,4071.105172,2353.333708,1932.131384,2321.379396,451.897136,508.233533,473.316852,548.024991,531.734121,0.0,3219.930006,1670.039158,1010.673126,1968.678346,280.289110,267.859765,312.065167,380.561340
1,947.711231,0.0,3900.914176,2277.842161,1690.477060,2166.641551,445.539934,506.571789,461.572278,512.208855,552.470091,0.0,3227.933095,1769.995053,852.420075,1907.074344,188.346927,170.497946,267.796770,323.783708
2,974.331007,0.0,3979.832492,2283.686274,1690.477060,2165.930026,448.172550,499.726600,469.960707,521.060870,606.749846,0.0,3223.038309,1617.791781,830.167334,1891.243759,230.452869,245.837623,275.209718,350.080290
3,929.652092,0.0,4058.525460,2352.148046,1683.018508,2224.372450,471.868073,516.859766,477.288038,553.178057,529.202307,0.0,3227.463917,1622.929891,962.142173,1980.635143,279.794976,274.405667,319.448417,370.855702
4,895.958474,0.0,4062.473695,2330.782194,1684.090194,2224.105852,470.075099,514.213112,477.658675,553.173204,499.394908,0.0,3227.463917,1624.682547,968.536128,1980.272893,287.833529,280.041318,328.468846,385.851825
5,644.067882,0.0,4012.815844,2299.177236,1600.575024,2173.660119,472.803458,514.955092,481.484652,550.629134,432.805423,0.0,3227.566963,1639.275797,909.645497,1908.231246,286.304133,276.534596,330.459572,383.097794
6,1016.452404,0.0,4034.229874,2387.482150,1572.520766,2277.346656,360.650678,322.500488,478.849097,529.475806,551.011784,0.0,2998.684328,1536.574300,731.722191,2017.181657,167.563533,175.800393,292.081346,314.651073
7,985.217797,0.0,4137.055301,2363.245491,1822.716331,2328.464018,404.498892,422.029509,518.887773,565.187181,591.388761,0.0,3025.943365,1802.192481,925.269186,2040.886044,198.787741,214.683081,320.753061,355.593520
8,999.667551,0.0,4107.805824,2383.149189,1774.526808,2334.702646,393.181212,405.129785,476.843816,544.573626,571.436990,0.0,2996.315753,1553.032408,911.766526,2106.833464,197.117148,215.561815,313.251207,353.146559
9,1070.151725,0.0,4022.776846,2325.119016,1652.339774,2175.773080,462.097499,490.674166,464.635553,541.996499,625.044782,0.0,3309.557743,1673.107040,990.247101,1957.937923,213.927270,228.239014,264.577291,336.330536