In [1]:
%matplotlib inline

import pandas as pd
import numpy as np

import seaborn as sns

import matplotlib.pyplot as plt

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [5]:
from gasopt import data_load

In [18]:
T = pd.read_csv('test-slab-input-furn1.csv', ';', encoding='cp1251')

In [19]:
T

   length_s  width_s  weight_s  slab_temp  l_thick  dt_prev  row   mark
0      4800     1340    12.273      112.0      2.0    0.007    2  Ст3пс
1      4800     1340    12.240      745.0      2.0  134.657    1  Ст3пс
2      4800     1340    12.240      720.0      2.0    0.003    2  Ст3пс
3      5000     1340    12.780      243.0      2.0  235.523    1  Ст3пс
4      5000     1340    12.780      242.0      2.0    0.010    2  Ст3пс
5      5000     1340    12.784      434.0      2.0  596.834    1  Ст3пс
6      6000     1270    14.540      672.0      2.5    0.003    2  other
7      6000     1270    14.540       55.0      2.5  371.590    1  other
8      6000     1270    14.540      280.0      2.5    0.003    2  other
9      9500     1340    24.240      507.0      2.0  176.357    2  Ст3пс

In [6]:
G = data_load.furn_optimization_data_process('test-slab-input-furn1.csv')

In [7]:
G

,length_s,width_s,weight_s,slab_temp,l_thick,dt_prev,row,mark,area_s,vacant_area,...,mark_14,mark_15,mark_16,mark_17,mark_18,mark_19,mark_20,t_unl,temp_gain,heat_gain
0,4800,1340,12.273,112,2,0.007,2,Ст3пс,6432000,3216000.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1250,1138,13966.7
1,4800,1340,12.24,745,2,134.657,1,Ст3пс,6432000,3216000.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1250,505,6181.2
2,4800,1340,12.24,720,2,0.003,2,Ст3пс,6432000,3216000.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1250,530,6487.2
3,5000,1340,12.78,243,2,235.523,1,Ст3пс,6700000,2680000.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1250,1007,12869.5
4,5000,1340,12.78,242,2,0.01,2,Ст3пс,6700000,2680000.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1250,1008,12882.2
5,5000,1340,12.784,434,2,596.834,1,Ст3пс,6700000,2680000.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1250,816,10431.7
6,6000,1270,14.54,672,2.5,0.003,2,other,7620000,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1250,578,8404.12
7,6000,1270,14.54,55,2.5,371.59,1,other,7620000,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1250,1195,17375.3
8,6000,1270,14.54,280,2.5,0.003,2,other,7620000,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1250,970,14103.8
9,9500,1340,24.24,507,2,176.357,2,Ст3пс,12730000,3350000.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1250,743,18010.3